version: '3'
services:
  tomcat:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: dropInRegistration
    ports: 
      - "8081:8080"
    volumes:
      - ./DropInRegistration.war:/usr/local/tomcat/webapps/dropInRegistration.war
      - ./data/:/home/dropInRegistration/
